name: Wasm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-host:

    runs-on: ubuntu-latest

    steps:
    - name: Wasm target
      run: rustup target add wasm32-unknown-unknown
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: cargo build --verbose --target wasm32-unknown-unknown
    - name: Build with feature thin
      run: cargo build --verbose --features thin --target wasm32-unknown-unknown

  build-windows-host:

    runs-on: windows-latest

    steps:
    - name: Wasm target
      run: rustup target add wasm32-unknown-unknown
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: cargo build --verbose --target wasm32-unknown-unknown
    - name: Build with feature thin
      run: cargo build --verbose --features thin --target wasm32-unknown-unknown

  build-macos-host:

    runs-on: macos-latest

    steps:
    - name: Wasm target
      run: rustup target add wasm32-unknown-unknown
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: cargo build --verbose --target wasm32-unknown-unknown
    - name: Build with feature thin
      run: cargo build --verbose --features thin --target wasm32-unknown-unknown
